siderolabs/pkgs

- pkg.yaml
This PR brings in the last alpha of v1.16.0 kubeadm.
> feat: upgrade kubeadm to v1.16.0-alpha.3

- Makefile
- kmod/pkg.yaml
- util-linux/pkg.yaml
In previous versions of this repo we pushed the base stage, but we no
longer do. In projects outside of this one, we were pulling files from
the base image. This adds packages for those files.
> fix: add kmod and util-linux

- syslinux/pkg.yaml
- xfsprogs/pkg.yaml
There are a few places where we are copying shared objects from the
toolchain's /lib. This moves to using the util-linux stage instead. This
ensures that all packages are being built against the version of
util-linux in this repo.
> fix: use util-linux stage for shared object dependency

- containerd/pkg.yaml
The containerd-shim binary is required at runtime.
> fix: build containerd-shim

- Pkgfile
- ca-certificates/pkg.yaml
See https://github.com/talos-systems/tools/pull/80
Also update Pkgfile shebang and updated ca-certificates checksums.
> feat: upgrade tools for Go 1.13.2 update

- Pkgfile
- containerd/pkg.yaml
- dosfstools/pkg.yaml
- eudev/pkg.yaml
- kmod/pkg.yaml
- musl/pkg.yaml
- runc/pkg.yaml
- socat/pkg.yaml
- util-linux/pkg.yaml
- xfsprogs/pkg.yaml
In previous versions of the toolchain we had a misconfigured linker that
did not have /usr/lib in its search path. This brings in a version of
the toolchain that does, and removes all the hacks we did to work around
this.
> fix: use default search path

- kernel/pkg.yaml
This PR updates the kernel version to 5.5.9
> chore: bump to latest stable kernel

- ca-certificates/pkg.yaml
- cni/pkg.yaml
- iptables/pkg.yaml
- kmod/pkg.yaml
- libseccomp/pkg.yaml
- musl/pkg.yaml
- runc/pkg.yaml
- socat/pkg.yaml
- util-linux/pkg.yaml
- xfsprogs/pkg.yaml
This PR updates all of our packages if they needed updates
Updated packages:
- ca-certificates
- cni
- iptables
- kmod
- libseccomp
- musl
- runc
- socat
- util-linux
- xfsprogs
> chore: update all packages with latest versions

- Pkgfile
> chore: bump tools for Go update to version 1.14.3

- cni/pkg.yaml
- iptables/pkg.yaml
- libressl/pkg.yaml
- linux-firmware/pkg.yaml
- lvm2/pkg.yaml
- xfsprogs/pkg.yaml
This PR bundles various pkg updates. Packages updated are:
- CNI
- IPTables
- LibreSSL
- Linux Firmware
- LVM2
- XFS Progs
> feat: update pkgs for talos v0.6.x release cycle

- Makefile
- lvm2/patches/disable-create_toolcontext-buffering.patch
- lvm2/patches/mlockall-default-config.patch
- lvm2/pkg.yaml
LVM2 depends on libaio. This patch ensures that we publish libaio.
There also is a change in newer versions of musl that causes LVM2
to segfault because stdout/stderr is closed. This adds a patch that
disables buffering in create_toolcontext function to prevent the
segfault.
> fix: publish libaio and disable buffering

- runc/pkg.yaml
From https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc90:
> NOTE: This release's artefacts were updated on 2020-07-30 to correct an
> LGPL compliance issue (we previously did not include the source code of
> libseccomp with our releases) and thus we had to recompile our runc
> binaries to be sure we were distributing the correct version of libseccomp.
> All of the binaries are still signed by the same maintainer key, and thus can
> still be easily validated.
Archive contains broken paths, so workaround was applied.
> fix: update sha sum for runc release file, workaround broken archive

- Makefile
Previous solution doesn't work for `make` >= 4.3.
> fix: update the way variable with space is set for make

- Makefile
- Pkgfile
- cryptsetup/pkg.yaml
- eudev/pkg.yaml
- libjson-c/pkg.yaml
- libpopt/pkg.yaml
- lvm2/patches/static-build.patch
- lvm2/pkg.yaml
This adds `cryptsetup` and related utilities. We can use those to enable
raw disk encryption or LUKS-based encryption.
We could use the integrity modules as well if we need to.
> feat: add `cryptsetup` build

- grub/patches/udev.patch
- grub/pkg.yaml
GRUB has a lot of ways to find partition start for each partition it's
working on. Some of them don't work for loopback devices (GETGEO ioctl),
some don't work inside container (getting to udevd via udevadm).
As in our case partition layout is fixed, we can simplify things a lot
by simply building correct sysfs path.
> fix: patch GRUB to allow install to loopback devices

- eudev/pkg.yaml
Hardware DB might make little sense for servers, so disable it to
reduce initramfs size.
> fix: disable hwdb in eudev

- containerd/pkg.yaml
This brings in the latest stable containerd.
> feat: upgrade containerd to v1.4.0

- Pkgfile
- ca-certificates/pkg.yaml
- ipmitool/patches/gcc-10.patch
- ipmitool/pkg.yaml
- musl/pkg.yaml
Also bump libmuslc to 1.2.1 (matches toolchain), fix gcc 10 build error
in ipmitool, and update ca-certificates to latest.
> feat: update to tools and new toolchain (incl. gcc 10.2.0)

- Pkgfile
This should speed up parallel builds on Linux 5.6+ kernels.
> chore: bump tools for Make 4.3

- kernel/kernel/pkg.yaml
See https://www.kernel.org/doc/Documentation/efi-stub.txt
> fix: use proper kernel image on arm64 for EFI stub

- .drone.yml
We need to specify the registry for `docker login`.
> chore: fix docker login

- kernel/kernel/pkg.yaml
Compiles the device-tree blobs required by SoC ARM64 boards.
> feat: compile dtbs

- containerd/pkg.yaml
This brings in the latest stable release of containerd.
> feat: update containerd to v1.4.2

- u-boot/pkg.yaml
The directory included "_defconfig" when it should not.
> fix: use the correct name for rpi4 install dir

- containerd/pkg.yaml
The third patch release for containerd 1.4 is a security release to address CVE-2020-15257.
See GHSA-36xw-fx78-c5r4 for more details.
> feat: update containerd to 1.4.3

- kernel/kernel/pkg.yaml
We need the `dtb` directory to exist so that it can be copied from in a
`Dockerfile`.
> fix: create dtb directory for all architectures

- .drone.yml
- Makefile
- raspberrypi-firmware/pkg.yaml
- u-boot/pkg.yaml
If we build arm64-only versions, they're pulled into the amd64 build of
Talos as well (as there's no amd64 counterpart).
> fix: build "empty" images for arm64 packages on amd64

- raspberrypi-firmware/pkg.yaml
- u-boot/pkg.yaml
Fix that by pushing empty directory for u-boot and raspberrypi-firmware
on amd64.
> fix: buildkit doesn't like pushing totally empty images

- kernel/kernel/config-amd64
Builds the `cdc-acm` module into the kernel.
> feat: enable CONFIG_USB_ACM

- kernel/kernel/pkg.yaml
We're not using uncompressed kernel anywhere, it's huge and it can't be
used directly in most of the cases.
> chore: drop vmlinux from kernel package

- Pkgfile
- musl/pkg.yaml
> feat: update libmusl to 1.2.2

- kernel/kernel/config-amd64
CONFIG_HYPERV_UTILS=y in the amd64 kernel config
Enabling this in the kernel makes running it on Hyper-V work better:
It enables running a hyper-v integration daemon, which is needed to enable things like setting a static IP address, copying files onto the server from the virtual machine manager.
To my surprise, it also means the wallclock time gets set correctly (as opposed to shifted by an hour because we're in GMT+1), so I guess it enables automatic time sync to the hyper-v host.
> feat: enable hyperv_utils in linux kernel

- Pkgfile
> chore: bump tools for Go 1.15.7 update

- cni/pkg.yaml
Build CNI plugins instead of downloading pre-built binaries.
Bump version to master to fix `ip6tables` issue:
https://github.com/containernetworking/plugins/pull/563
> feat: build CNI plugins, bump version to current master

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
- kernel/kernel/scripts/filter-hardened-check.py
KSPP doesn't strictly require init_on_free=1:
```
The init_on_free is only needed if there is concern about minimizing stale data lifetime.
```
It has significant performance impact:
```
Slowdown for the new features compared to init_on_free=0,
init_on_alloc=0:
hackbench, init_on_free=1:  +7.62% sys time (st.err 0.74%)
hackbench, init_on_alloc=1: +7.75% sys time (st.err 2.14%)
Linux build with -j12, init_on_free=1:  +8.38% wall time (st.err 0.39%)
Linux build with -j12, init_on_free=1:  +24.42% sys time (st.err 0.52%)
Linux build with -j12, init_on_alloc=1: -0.13% wall time (st.err 0.42%)
Linux build with -j12, init_on_alloc=1: +0.57% sys time (st.err 0.40%)
```
And it causes all the RAM to be allocated (touched) on boot which causes
problems with virtualized environments in memory …
> feat: update Linux to 5.10.17, disable init_on_free=1 by default

- u-boot/pkg.yaml
This PR pulls in an RC of u-boot that contains the fixes necessary to
get USB support on rpi to work properly.
> feat: upgrade u-boot to 2021.04-rc3

- .gitattributes
Looks like an overkill for such a small files, while it brings issues
in our CI pipeline as you have to install git-lfs there.
Signed-off-by: Artem Chernyshev <artem.0xD2@gmail.com>
> chore: do not use git-lfs for rockpi4 binaries

- u-boot/pkg.yaml
This PR upgrades uboot to latest and greatest stable release to get us
off of an RC.
> feat: update uboot to 2021.04 stable

- Pkgfile
No changes, just image tag update.
> chore: update tools tag to v0.5.0

- containerd/pkg.yaml
- runc/pkg.yaml
This is a direct update in release-0.5 branch (for Talos 0.10), as
master is already at containerd 1.5.0.
> feat: update containerd to 1.4.5, runc to 1.0.0-rc94

- libseccomp/pkg.yaml
- runc/pkg.yaml
See https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc95
This addresses
[CVE-2021-30465](https://github.com/opencontainers/runc/security/advisories/GHSA-c3xm-pvg7-gh7r).
> feat: update runc to 1.0.0-rc95

- containerd/pkg.yaml
runc was already updated to 1.0.0-rc95
See https://github.com/containerd/containerd/releases/tag/v1.5.2
> feat: update containerd to 1.5.2

- containerd/pkg.yaml
runc was already updated to 1.0.0-rc95
See https://github.com/containerd/containerd/releases/tag/v1.4.6
> feat: update containerd to 1.4.6

- Pkgfile
This should match upcoming Talos 0.11 release.
> chore: bump tools to final release 0.6.0

- containerd/pkg.yaml
- runc/pkg.yaml
This pulls current definitions from master:
* containerd 1.5.5
* runc 1.0.1
This addresses security vulnerability
[CVE-2021-32760](https://github.com/containerd/containerd/security/advisories/GHSA-c72p-9xmj-rx3w).
> feat: update containerd and runc versions

- grub/patches/efi-fat-serial-number.patch
- grub/pkg.yaml
This adds a patch to force FAT serial number for the EFI partition.
> chore: patch grub with support for reproducible ISO builds

- Pkgfile
See https://github.com/talos-systems/tools/pull/144
> chore: bump tools for Go 1.16.7

- ipxe/pkg.yaml
As we build from tarball, iPXE can't set its version based on git tags.
> fix: set iPXE version properly

- util-linux/pkg.yaml
See https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.37/v2.37-ReleaseNotes
> feat: bump util-linux to 2.37

- raspberrypi-firmware/pkg.yaml
> feat: bump raspberrypi-firmware to 1.20210805

- Makefile
- Pkgfile
This pulls in bldr with support HTTP_PROXY and also pushes http_proxy
environment variables to the build environment.
> chore: support builds with HTTP_PROXY

- Pkgfile
> chore: update tools

- containerd/pkg.yaml
- libseccomp/pkg.yaml
- runc/pkg.yaml
Update container runtime components.
Containerd release contains a fix for CRI plugin config merge.
> feat: update containerd to 1.5.6, runc to 1.0.2, libseccomp to 2.5.2

- containerd/pkg.yaml
- kernel/kernel/scripts/filter-hardened-check.py
- libseccomp/pkg.yaml
- runc/pkg.yaml
Update container runtime components.
Containerd release contains a fix for CRI plugin config merge.
(cherry picked from commit f22ce181d8dae3481a011772e92029d6ef351cc5)
(backporting for Talos 0.12.x)
> backport: feat: update containerd to 1.5.6, runc to 1.0.2, libseccomp to 2.5.2

- containerd/pkg.yaml
This PR updates the shas that result from the github generated tars
:facepalm:
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> fix: update containerd shas

- libseccomp/pkg.yaml
To use the same version as tools.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> feat: update libseccomp to 2.5.3

- .conform.yaml
- raspberrypi-firmware/pkg.yaml
in order to be able to enable `arm_boost`. arm_boost will add 300Mhz to the clockspeed of newer broadcom CPUs
> feat: bump raspberrypi-firmware to 1.20211029

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.5.8
> feat: update containerd to 1.5.8

- libressl/pkg.yaml
See https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.2.7-relnotes.txt
Signed-off-by: Nico Berlee <nico.berlee@on2it.net>
> chore: update LibreSSL to 3.2.7

- Makefile
- ca-certificates/pkg.yaml
- cni/pkg.yaml
- flannel-cni/pkg.yaml
Flannel got moved out to its own repository, so we have to build it as a
separate package.
> feat: update CNI to 1.0.1, separate package for flannel

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
Full release notes: https://lwn.net/Articles/877286/
Please note: scsi: sd: Fix sd_do_mode_sense() buffer length handling
(disk cache may fail on 5.15.5: https://bugzilla.kernel.org/show_bug.cgi?id=215137)
Signed-off-by: Nico Berlee <nico.berlee@on2it.net>
> feat: update Linux to 5.15.6

- u-boot/pkg.yaml
Bump u-boot to 2022.01
Also fixes a USB reset bug on Raspberry Pi when using the pre-released firmware
```bash
U-Boot 2021.10 (Dec 27 2021 - 16:06:23 +0000)
DRAM:  7.9 GiB
RPI 4 Model B (0xd03114)
MMC:   mmcnr@7e300000: 1, mmc@7e340000: 0
Loading Environment from FAT... Card did not respond to voltage select! : -110
In:    serial
Out:   vidconsole
Err:   vidconsole
Net:   eth0: ethernet@7d580000
PCIe BRCM: link up, 5.0 Gbps x1 (SSC)
starting USB...
Bus xhci_pci: Register 5000420 NbrPorts 5
Starting the controller
USB XHCI 1.00
scanning bus xhci_pci for devices... Unexpected XHCI event TRB, skipping... (3d8e36a0 00000004 01000000 01008401)
BUG at drivers/usb/host/xhci-ring.c:503/abort_td()!
BUG!
resetting ...
```
> chore: bump u-boot to 2022.01

- containerd/pkg.yaml
- runc/pkg.yaml
In preparation for 1.6.0 we should make sure it works fine with Talos.
> feat: bump containerd to 1.6.0-rc.0, runc to 1.1.0

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.18

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.19

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bump kernel to 5.15.21 stable
https://www.openwall.com/lists/oss-security/2022/02/04/1 fixed in
5.15.20
> chore: bump kernel to 5.15.21

- Pkgfile
See https://github.com/talos-systems/tools/pull/168
> chore: bump tools for Go 1.17.7

- Pkgfile
See https://github.com/talos-systems/tools/pull/169
> backport: chore: update tools for Go 1.17.7

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.24

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kenrel to 5.15.25

- cni/pkg.yaml
See https://github.com/containernetworking/plugins/releases/tag/v1.1.0
> feat: update CNI plugins to v1.1.0

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bump kernel to 5.15.26
Fixes [CVE-2022-25636](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25636)
> chore: bump kernel to 5.15.26

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.5.10
This is backport for Talos 0.14.
> feat: update containerd to 1.5.10

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
Fixes [CVE-2022-25636](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25636)
> feat: update Linux to 5.15.26 (backport for Talos 0.14)

- Pkgfile
Update Golang to 1.17.8
Ref: https://github.com/talos-systems/tools/pull/174
> chore: Update golang to 1.17.8

- Makefile
- Pkgfile
- base/pkg.yaml
- openssl/pkg.yaml
- u-boot/pkg.yaml
* use bldr with support for SOURCE_DATE_EPOCH
* use latest tools v1.0.0 + go 1.17.8
* publish `base` image to be re-used in extras and extensions
> chore: reproducible builds

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.27

- nonfree/kmod-nvidia/pkg.yaml
> chore: bump nvidia driver to 510.54

- linux-firmware/pkg.yaml
Bump linux-firmware to 20220310
> chore: bump linux-firmware to 20220310

- nonfree/kmod-nvidia/pkg.yaml
Enable aarch64(arm64) NVIDIA drivers
> chore: enable aarch64 NVIDIA drivers

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.30

- flannel-cni/pkg.yaml
See https://github.com/flannel-io/cni-plugin/releases/tag/v1.0.1
> feat: update Flannel CNI to 1.0.1

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.31

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.2
Contains a fix for https://github.com/containerd/containerd/security/advisories/GHSA-c9cp-9c75-9v8c
(cherry picked from commit a76edfdf941455237f8f16b7a833233257ae63a4)
> feat: update containerd to 1.6.2

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.32

- nonfree/kmod-nvidia/pkg.yaml
Bump NVIDIA drivers to 510.60.02
> chore: bump nvidia drivers to 510.60.02

- Pkgfile
Update tools to v1.1.0-alpha.0-5
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
> chore: update to use latest tools (specifically go 1.18)

- ipxe/pkg.yaml
Fixes iPXE prompt hanging on ARM64
The fix is not added as a patch since `src/config/local` is supposed to
be user fixes added in iPXE and gitignored by the iPXE project
Fixes: https://github.com/siderolabs/sidero/issues/806
> fix: ipxe prompt arm64

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bump kernel to 5.15.33 stable
Also bump tools (ref: https://github.com/siderolabs/tools/pull/182)
> chore: bump kernel to 5.15.33

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.34

- linux-firmware/pkg.yaml
Bump linux-firmware to 20220411
> chore: bump linux-firmware 20220401

- raspberrypi-firmware/pkg.yaml
Bump raspberrypi-firmware to 1.20220331
This allows to use the upstream kernel PoE hat driver
Ref: https://github.com/raspberrypi/firmware/commit/69277bc713133a54a1d20554d79544da1ae2b6ca
> chore: bump raspberrypi-firmware to 1.20220331

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.35

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.37

- Pkgfile
- ca-certificates/pkg.yaml
Bump ca-certificates to 2022-04-26
Bump [tools](https://github.com/siderolabs/tools/pull/193)
> chore: bump ca-certificates to 2022-04-26

- containerd/pkg.yaml
Bump containerd to v1.6.4
Ref:
- https://github.com/containerd/containerd/releases/tag/v1.6.4
- https://github.com/containerd/containerd/commit/212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
> chore: bump containerd to v1.6.4

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.38

- nonfree/kmod-nvidia/pkg.yaml
Bump nvidia drivers to 510.68.02
> chore: bump nvidia drivers to 510.68.02

- runc/pkg.yaml
Bump runc to v1.1.2
Fixes: [CVE-2022-29162](https://www.openwall.com/lists/oss-security/2022/05/12/1)
> chore: bump runc to v1.1.2

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.39

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.40

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.41

- eudev/files/66-azure.rules
- eudev/pkg.yaml
Create symlinks root/resource devices to /dev/disk/azure folder.
Currently, Azure CSI uses folder /dev/drive/azure to define the boot/temporary disks.
It helps to find the disk by LUN number (removes the system disks from result).
Signed-off-by: Serge Logvinov <serge.logvinov@sinextra.dev>
> feat: azure boot disk defenition

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.43

- flannel-cni/pkg.yaml
See https://github.com/flannel-io/cni-plugin/releases/tag/v1.1.0
> feat: update Flannel CNI to 1.1.0

- Pkgfile
In preparation for Talos 1.1.0-beta release.
> chore: bump tools to final v1.1.0 release

- Pkgfile
Bump Golang to [1.17.11](https://github.com/siderolabs/tools/pull/202)
> chore: bump golang to 1.17.11

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.5
(cherry picked from commit b1c207d63b1cac99b90025d530c57da4f51fc652)
> feat: update containerd to 1.6.5

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.6
(cherry picked from commit b9c72a59cd6077ceb0ce53f11241d294c137f68b)
> feat: update containerd to 1.6.6

- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.46

- nonfree/kmod-nvidia/pkg.yaml
Bump Nvidia driver to 515.43.04
> chore: bump nvidia driver to 515.43.04

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.47

- nonfree/kmod-nvidia/pkg.yaml
Bump NVIDIA proprietary drivers to 515.48.07
> chore: bump nvidia drivers to 515.48.07

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bump kernel to 5.15.48
Mitigates processor [MMIO vulnerabilities](https://lwn.net/Articles/898011/)
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=441947019138
Fixes:
- [CVE-2022-21166](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21166)
- [CVE-2022-21125](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21125)
- [CVE-2022-21123](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21123)
> chore: bump kernel to 5.15.48

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bump kernel to 5.15.49 LTS
Enable `RANDOM_TRUST_BOOTLOADER` by default
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=846bb97e131d7938847963cca00657c995b1fce1
> chore: bump kernel to 5.15.49

- Pkgfile
- openssl/pkg.yaml
Bump OpenSSL to [1.1.1p](https://github.com/siderolabs/tools/pull/204)
> chore: bump openssl to 1.1.1p

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.52

- Pkgfile
- openssl/pkg.yaml
Bump OpenSSL to [1.1.1q](https://github.com/siderolabs/tools/pull/206)
> chore: bump openssl to 1.1.1q

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.53

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bump kernel to 5.15.54
contains backported fix for [CVE-2022-34918](https://nvd.nist.gov/vuln/detail/CVE-2022-34918)
> chore: bump kernel to 5.15.54

- Pkgfile
See https://github.com/siderolabs/tools/pull/208
> backport: chore: update Go to 1.18.4

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.58

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.59

- nonfree/kmod-nvidia/pkg.yaml
Bump nvidia drivers to 515.65.01
> chore: bump nvidia drivers to 515.65.01

- Makefile
- nvidia-open-gpu-kernel-modules/pkg.yaml
Add NVIDIA open gpu kernel modules
Ref: https://developer.nvidia.com/blog/nvidia-releases-open-source-gpu-kernel-modules/
> feat: add nvidia open gpu kernel modules

- containerd/pkg.yaml
Bump containerd to [v1.6.8](https://github.com/containerd/containerd/releases/tag/v1.6.8)
> chore: bump containerd to v1.6.8

- u-boot/pkg.yaml
This PR adds the u-boot configuration for building the bootloader of the NanoPi R4S. This will remain a draft until the corresponding PR in the talos repo is ready and opened as well.
> feat: add NanoPi R4S configuration

- Pkgfile
- ipxe/patches/silence-gcc-12-spurious-warnings.patch
- ipxe/pkg.yaml
- musl/pkg.yaml
- u-boot/arm-trusted-firmware/patches/gcc-12-build-fix.patch
- u-boot/pkg.yaml
Bump gcc to [12.2.0](https://github.com/siderolabs/tools/pull/214)
Bump musl to 1.2.3
Bump ipxe and apply fix for building ipxe with gcc 12, ref:
- https://github.com/ipxe/ipxe/issues/620
- https://github.com/openSUSE/qemu-ipxe/commit/1dcf6506629ae
Bump ARM trusted firmware to v2.7 and add similar patch like ipxe
> chore: bump gcc to 12.1.0

- Makefile
- nvidia-open-gpu-kernel-modules/pkg.yaml
Fix conflicting `pkg` and `extensions` image name.
> fix: nvidia oss pkg name

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.63

- runc/pkg.yaml
Bump runc to [v1.1.4](https://github.com/opencontainers/runc/releases/tag/v1.1.4)
> chore: bump runc to v1.1.4

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bump kernel to 5.15.64
Fixes: CVE-2022-2905
> chore: bump kernel to 5.15.64

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.67

- Makefile
- Pkgfile
- gasket-driver/pkg.yaml
- test/pkg.yaml
This driver enables the use of [Coral.ai](https://coral.ai/)'s PCIe TPU modules.
Signed-off-by: Branden Cash <203336+ammmze@users.noreply.github.com>
Required-by: siderolabs/extensions#69
> feat: added gasket driver package

- .github/renovate.json
- Pkgfile
Rollback xfsprogs to 5.18.0.
Talos [state partition](https://github.com/siderolabs/talos/blob/main/internal/pkg/partition/constants.go#L37) uses a 100MiB partition size of xfs type. Since xfsprogs 5.19.0 paritions of size less than 300MiB are not allowed. For now it doesn't make sense to increase the Talos `STATE` partition size from 100MiB to 300MiB just to make it work with newer xfsprogs. Until Talos has a use case for larger `STATE` partition or a different filesystem type for `STATE` partition, keep xfsprogs locked to `< 5.19.0` allowing minor fixes if any.
Ref: https://fossies.org/linux/xfsprogs/doc/CHANGES
From the xfsprogs [code](https://fossies.org/linux/xfsprogs/mkfs/xfs_mkfs.c):
```text
2523     /*
2524      * We don't support filesystems smaller than 300MB anymore.  Tiny
2525 …
```
> fix: rollback xfsprogs to 5.18.0

- .drone.yml
- Pkgfile
The slack trigger was already having status set in the step itself, so remove that and only use the trigger.
> chore: disable drone slack pipeline for renovate

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.69

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> chore: bump kernel to 5.15.70

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> chore: bump kernel to 5.15.72

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
There seems to be a bug with arm64/UEFI introduced in 5.15.68..5.15.72.
> feat: revert kernel to 5.15.68

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/patches/uefi-no-randomize.patch
- kernel/prepare/pkg.yaml
Use patch from https://lore.kernel.org/all/CAMj1kXH7462XEBis6wL-AOXfDBv-1iKKAn4fOPaKRve1fHkDzQ@mail.gmail.com/T/
This reverts commit 08408bb8f7f9d68234d7875c3fb9d2ea0876ab33.
> feat: revert kernel to 5.15.72, add UEFI no randomize patch

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/patches/uefi-no-randomize.patch
- kernel/prepare/pkg.yaml
* Linux: 5.15.73
* ipxe: 6b2c94d3a7d93a8fc47fcb0b895477d4dafca5f0
* xz: 5.2.7
* libpopt: 1.19
* openssl: 1.1.1r
Also import UEFI/arm64 kernel fix from `release-1.2`.
> feat: update dependencies

- Makefile
- Pkgfile
- drbd/pkg.yaml
I have currently issues with caching in my build environment, so I was not able to test it end-to-end (with installer image). While fixing my environment, I would like to provide everything, what I hava so far...
Would be great if, someone with an ARM system could test it!
A possible use (and test) case is installation of [piraeus-operator](https://github.com/piraeusdatastore/piraeus-operator) following command for helm:
```
helm install \
--set operator.satelliteSet.kernelModuleInjectionMode=None \
--set etcd.enabled=false \
--set controller.dbConnectionURL=k8s \
piraeus-op \
./charts/piraeus
```
> feat: add 'drbd' package

- Makefile
- drbd/pkg.yaml
Add the `-pkg` suffix to the drbd pkg.
> fix: drbd package name

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Updates:
* Linux kernel 5.15.74
* Linux firmware 20221012
Reverts
* openssl 1.1.1q (see https://mta.openssl.org/pipermail/openssl-announce/2022-October/000237.html)
Signed-off-by: Tim Jones <tim.jones@siderolabs.com>
> chore: update dependencies

- Pkgfile
Also update xz to 5.2.9 to match tools.
> backport: feat: update Go 1.19.4, containerd to 1.6.11

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v1.6.12
Fixes [CVE-2022-23471](https://github.com/advisories/GHSA-2qjp-425j-52j9).
> backport: feat: update containerd to 1.6.12

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Updating to the latest LTS release before Talos 1.3.0.
> backport: feat: update Linux to 5.15.83

- Pkgfile
- containerd/pkg.yaml
- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Bring release-1.2 to match release-1.3 for critical/security fixes.
> backport: feat: update Go 1.19.4, Linux 5.15.83, containerd 1.6.12

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Update dependencies for upcoming Talos 1.3.1.
> backport: feat: Linux 5.15.85, containerd 1.6.14

- base/pkg.yaml
- ipxe/pkg.yaml
Use default symlinks from `/toolchain/bin` to `/bin` in `base`.
> chore: use default symlinks to `/bin` in `base`

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
See https://github.com/containerd/containerd/releases/tag/v1.6.15
> backport: feat: Linux 5.15.86, containerd 1.6.15

- kernel/build/config-amd64
- kernel/build/config-arm64
Magic Sysrq should not be enabled by default.
Fixes #645.
Also ran the missing `make kernel-olddefconfig`
Re-created from #646
(cherry picked from commit 4234510651ec4733513991940f9805fa9405827e)
> fix: disable magic sysrq

- u-boot/pkg.yaml
- u-boot/rpi_arm64/0002-rpi-add-NVMe-to-boot-order.patch
- u-boot/rpi_arm64/0003-Revert-nvme-Correct-the-prps-per-page-calculation-me.patch
- u-boot/rpi_arm64/0004-usb-xhci-brcm-Make-driver-compatible-with-downstream.patch
- u-boot/rpi_arm64/0005-nvme-improve-readability-of-nvme_setup_prps.patch
- u-boot/rpi_arm64/0006-nvme-Use-pointer-for-CPU-addressed-buffers.patch
- u-boot/rpi_arm64/0007-nvme-translate-virtual-addresses-into-the-bus-s-addr.patch
- u-boot/rpi_arm64/0008-enable-nvme-and-fixup-efi-boot.patch
> ~Note: Boot offset is still wrong; still checking; manually booting works~
>
> Edit: works fine now 🎉 
This allows the RaspberryPi CM4 to use an M.2 NVMe SSD as boot drive.
It also contains a fix for https://github.com/siderolabs/pkgs/issues/658
Fixes https://github.com/siderolabs/talos/issues/5912
Signed-off-by: Matthias Riegler <me@xvzf.tech>
> feat: enable nvme support for rpi_generic

- Makefile
- Pkgfile
- mellanox-ofed/pkg.yaml
Mellanox OFED drivers, currently this only builds with kernel 5.15
series, so keep it disabled until there's a new version that builds with
kernel 6.1
> feat: mellanox oped

- drbd/pkg.yaml
- gasket-driver/pkg.yaml
- nonfree/kmod-nvidia/pkg.yaml
- nvidia-open-gpu-kernel-modules/pkg.yaml
https://github.com/siderolabs/talos/issues/6751 was not a complete fix for https://github.com/siderolabs/talos/issues/6681. This fixed all driver builds to copy over `modules.builtin` and also make sure they are installed in `extras` so that proper module dependency tree is generated by Talos on installing drivers built as extensions.
> fix: missing kernel module tree files

- .github/renovate.json
- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
- nonfree/kmod-nvidia/pkg.yaml
Update dependencies.
Also fixes renovate lookup for nvidia driver.
> chore: bump deps

- Pkgfile
Fixes 2 CVEs
See https://github.com/containerd/containerd/releases/tag/v1.6.18
> feat: update containerd to 1.6.18

- Pkgfile
- liblzma/pkg.yaml
Sourcefource url's are prone to providing different file shasums at times. Fix by using from xz git repo releases.
> fix: sourcefourge url shasums

- Makefile
- Pkgfile
- mellanox-ofed/pkg.yaml
drbd now builds with Linux 6.1.
Also update mellanox version.
> chore: re-enable drbd

- Makefile
Reorder the build so that kernel-related packages are closer to the kernel, this way we should lower the probability of the cache purge for the kernel build.
> chore: reorder pkgs for better kernel caching

- kernel/kernel/pkg.yaml
Copy over the kernel signing public key so that it can be used to verify modules are signed by the correct key. The signing key is copied over as otherwise in-order to extract the signing key we either need the uncompressed `vmlinux` (which is super huge to copy over) or need the `System.map` file along with `vmlinuz` and a perl script to extract it. It's just easier to just copy over the `signing_key.x509` file.
> chore: copy over the kernel signing public key

- kernel/kernel/pkg.yaml
Copy over the kernel signing public key so that it can be used to verify modules are signed by the correct key. The signing key is copied over as otherwise in-order to extract the signing key we either need the uncompressed `vmlinux` (which is super huge to copy over) or need the `System.map` file along with `vmlinuz` and a perl script to extract it. It's just easier to just copy over the `signing_key.x509` file.
(cherry picked from commit 4eae958770573613bc29568d130be7aaa775e530)
> backport: chore: copy over the kernel signing public key

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest LTS in 6.1.x.
(cherry picked from commit 988f1ecf95536fb259cbd79e044a556728bc7332)
> backport: feat: update Linux to 6.1.24

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> chore: bump kernel to 6.1.28

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Update tools with go1.20.5.
Linux 6.1.32, openssl 1_1_1u, ipxe.
> feat: bump dependencies

- usb-modem-drivers/files/modules.txt
Copy missing `modules.order`, `modules.builtin` and `modules.builtin.modinfo` files so tools can read them.
> fix: copy missing `modules.*` files

- Pkgfile
Bump drbd to a non-broken version.
Fixes: https://github.com/siderolabs/extensions/issues/155
> fix: bump drbd to 9.2.4

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
This release contains a workaround for
[Zenbleed](https://lock.cmpxchg8b.com/zenbleed.html).
> feat: update Linux to 6.1.41

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
This release contains a workaround for
[Zenbleed](https://lock.cmpxchg8b.com/zenbleed.html).
> backport: feat: update Linux to 6.1.41

- Pkgfile
- flannel-cni/pkg.yaml
- kernel/build/config-amd64
- kernel/build/config-arm64
- nonfree/kmod-nvidia/pkg.yaml
|---|---|---|
| [benhoyt/inih](https://togithub.com/benhoyt/inih) | major | `56` -> `57` | 
| [nvidia/open-gpu-kernel-modules](https://togithub.com/nvidia/open-gpu-kernel-modules) | major | `530.41.03` -> `535.34.03` | 
| [containerd/containerd](https://togithub.com/containerd/containerd) | minor | `v1.6.21` -> `v1.6.22` | 
| [flannel-io/cni-plugin](https://togithub.com/flannel-io/cni-plugin) | minor | `v1.1.2` -> `v1.2.0` | 
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.1.41` -> `6.1.42` | 
| https://github.com/ipxe/ipxe.git | digest | `e17568a` -> `c1834f3` |
> chore: bump dependencies

- Pkgfile
Prepare for Talos 1.5 release of pkgs.
> feat: update Go to 1.20.7, OpenSSL to 1.1.1v

- .drone.yml
At the moment it is kmod-nvidia.
(cherry picked from commit 30cd5846bd7a9cbf5e79c23b9e42a65a213276e2)
> chore: enable pushing of non-free packages

- Pkgfile
This is backport for Talos 1.4.8.
> backport: chore: update Go to 1.20.7

- Pkgfile
See https://github.com/opencontainers/runc/releases/tag/v1.1.9
(cherry picked from commit eda123ddbd7ea5682ffe62164c41daf8ba531416)
> backport: feat: update runc to 1.1.9

- Makefile
- nonfree/kmod-nvidia/pkg.yaml
Add `-pkg` suffix to nonfree kmod nvidia.
(cherry picked from commit c4eac999135f8669d8f3f2d330b6208ae804cc86)
> fix: nonfree kmod pkg name

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest version in the 6.1.x LTS (for Talos 1.5.0 release).
> backport: feat: update Linux to 6.1.45

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest LTS release.
(cherry picked from commit cca80b7b939a2e5eb4769cc9e84d471bc4a6aec1)
> backport: feat: update Linux to 6.1.46

- ca-certificates/pkg.yaml
Make the cacert file world readable, so kresfied projects running an non-root user can access CA.
Part of fixing: https://github.com/siderolabs/talos-backup/issues/7
Before:
```bash
❯ ls -l _out/etc/ssl/certs/
.rw------- 221k frezbo  2 Jun  2019 ca-certificates
```
After:
```bash
❯ ls -l _out/etc/ssl/certs/
.rw-r--r-- 221k frezbo  2 Jun  2019 ca-certificates
```
> chore: fix cacert perms

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest LTS release for Talos 1.5.2.
> feat: update Linux to 6.1.51

- kernel/build/pkg.yaml
- kernel/prepare/pkg.yaml
`kconfig-hardened-check` -> `kernel-hardening-checker`
Upstream renamed: https://github.com/a13xp0p0v/kernel-hardening-checker/pull/85
(cherry picked from commit 4504f83f668776161af56853c3faec61edc4cdb6)
> chore: rename kconfig-hardened-check

- .kres.yaml
- Makefile
Fixes the kernel target to honor the `PLATFORM` variable.
> chore: fix kernel target to honor `PLATFORM`

- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- lvm2/pkg.yaml
Attempt to fix the reboot loop that happens when Talos encounters a disk that has lvm-thin volumes on it during boot.
Fixes #833
> feat: lvm2 thin support

- Pkgfile
- grub/pkg.yaml
Update grub to `2.12~rc1` to fix loading large initramfs.
Fixes: https://github.com/siderolabs/extensions/issues/272
> fix: update grub to fix loading large initramfs

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Last set of bumps before Talos 1.6.0-beta.0.
|---|---|---|
| [containerd/containerd](https://togithub.com/containerd/containerd) | patch | `v1.7.9` -> `v1.7.10` |
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.1.63` -> `6.1.64` |
> feat: bump depenendencies

- Pkgfile
See https://github.com/openzfs/zfs/releases/tag/zfs-2.1.14
This contains a critical data corruption fix.
> feat: update zfs to 2.1.14

- .github/renovate.json
- Pkgfile
Also fix renovate.json to correctly handle single-digit patch versions.
> feat: update zfs to v2.2.2

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Also other bumps:
|---|---|---|
| [containernetworking/plugins](https://togithub.com/containernetworking/plugins) | minor | `v1.3.0` -> `v1.4.0` |
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.1.64` -> `6.1.65` |
| git://git.kernel.org/pub/scm/utils/util-linux/util-linux.git | patch | `2.39.2` -> `2.39.3` |
| [seccomp/libseccomp](https://togithub.com/seccomp/libseccomp) | patch | `2.5.4` -> `2.5.5` |
> feat: update Go to 1.21.5

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> backport: feat: update Go to 1.21.5

- Pkgfile
- grub/pkg.yaml
This reverts commit 70919d82a594390392a2ebfe3b60beeeb7e00706.
Newer grub has issues with loading from XFS filesystems. See https://github.com/siderolabs/talos/issues/8023, and the fix in `70919d82` cannot be backported to older version. So the safe option is to revert while https://github.com/siderolabs/extensions/issues/272 remains open.
> fix: revert: update grub to fix loading large initramfs

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Hopefully should be the final Talos 1.6.0 Linux kernel version.
(cherry picked from commit 97270a2c26a9c61c2fff5fb104ff0a2bc9fbdd5d)
> backport: feat: update Linux to 6.1.67

- zfs/pkg.yaml
Since zfs moved all modules to `zfs` and `spl`, the build step needs to be updated.
> fix: zfs module build

- kernel/build/config-amd64
- kernel/build/config-arm64
For use in the extension: https://github.com/siderolabs/extensions/pull/296
Related Issue: https://github.com/siderolabs/extensions/issues/295
> feat: add v4l usb video class (webcam) drivers

- .github/renovate.json
- Pkgfile
- raspberrypi-firmware/pkg.yaml
Switch to using Git Ref for Raspberry Pi firmware. The repository stopped tagging releases.
Fixes: #870
> chore: switch to git ref for raspberrypi firmware

- Pkgfile
Containerd and runc bump for [CVE-2024-21626](https://github.com/advisories/GHSA-xr7r-f8xq-vfvv)
Part of #878
> chore: bump runc+containerd

- kernel/build/config-amd64
AMD KFD support was not enabled in Kconfig.
Ref: https://cateee.net/lkddb/web-lkddb/HSA_AMD.html
Fixes: #892
Fixes: https://github.com/siderolabs/extensions/issues/307
(cherry picked from commit 65006ed198f31e97a77ddfded52043182f2c6e92)
> fix: enable KFD support in kernel

- iptables/pkg.yaml
- lvm2/pkg.yaml
Removes binaries that rely on bash or are symlinked to lvm
> chore: remove symlinks and broken binaries

- Makefile
Enabled in #905, but I failed to re-kres.
> chore: re-enable zfs pkg

- Pkgfile
- liblzma/pkg.yaml
This downgrades xz version to `v5.4.5` which is the same version other distros have downgraded to.
Sidero repos are not affected, just downgrading as a safe precaution.
Ref: https://www.openwall.com/lists/oss-security/2024/03/29/4
Also pulls in the latest stable tools.
> fix: xz vulnerability

- kernel/build/config-amd64
This should resolve #941 and address https://github.com/siderolabs/talos/issues/8595 .
Before:
After:
However I'm not sure how it will affect AMD CPUs - I assume this option will be ignored?
> feat(intel): add support for power management and ACPI options for Intel CPUs

- drbd/pkg.yaml
Without this fix, no kernel modules are installed.
> fix: drbd module installation

- Pkgfile
Version: dc118c53696af6a0b1a8ee78fc9a4d28a217fb21
> feat: update ipxe to the latest

- Pkgfile
This is 1.7-only, as main is using contianerd 2.x.
See https://github.com/containerd/containerd/releases/tag/v1.7.18
> feat: update containerd to 1.7.18

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- apparmor/pkg.yaml
- reproducibility/pkg.yaml
Include AppArmor userland tool /sbin/apparmor_parser in rootfs to enable AppArmor support in containerd
As discussed in https://github.com/siderolabs/talos/issues/8715
> feat: add 'apparmor' package

- Pkgfile
See https://github.com/opencontainers/runc/releases/tag/v1.1.14
* Fix [CVE-2024-45310][cve-2024-45310], a low-severity attack that allowed maliciously configured containers to create empty files and directories on the host.
[cve-2024-45310]: https://github.com/opencontainers/runc/security/advisories/GHSA-jfvp-7x6p-h2pv
> feat: update runc to 1.1.14

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
- runc/pkg.yaml
|---|---|---|
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.6.47` -> `6.6.49` |
| git://git.kernel.org/pub/scm/utils/cryptsetup/cryptsetup.git | patch | `2.7.4` -> `2.7.5` |
| https://github.com/ipxe/ipxe.git | digest | `748cab7` -> `c7f2e75` |
| [opencontainers/runc](https://redirect.github.com/opencontainers/runc) | patch | `v1.2.0-rc.2` -> `v1.2.0-rc.3` |
runc update: https://github.com/opencontainers/runc/releases/tag/v1.2.0-rc.3
Fix CVE-2024-45310, a low-severity attack that allowed maliciously configured containers to create empty files and directories on the host.
> feat: bump releases

- Pkgfile
|---|---|---|
| [openssl/openssl](https://redirect.github.com/openssl/openssl) | patch | `3.3.1` -> `3.3.2` |
| [openzfs/zfs](https://redirect.github.com/openzfs/zfs) | patch | `2.2.5` -> `2.2.6` |
> feat: update Go 1.22.7, other bumps

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest Linux LTS for Talos 1.8.0.
> feat: update Linux to 6.6.52

- lvm2/pkg.yaml
LVM2 configure uses `AC_PATH_TOOL` to find modprobe path if not set, as we're building inside tools it was picking up `/toolchain/bin/modprobe`. Explicitly set `MODPROBE_CMD=/sbin/modprobe` to the path of `modprobe` binary in talos.
Fixes: https://github.com/siderolabs/talos/issues/9300
> fix: lvm2 modprobe path

- Makefile
- Pkgfile
- libattr/pkg.yaml
- xfsprogs/pkg.yaml
It's not quite evident why libattr started to be a hard dependency in 6.10.
Do we need to drop some progs we don't use?
Probably needs libattr in Talos rootfs as well.
> feat: update xfsprogs 6.10.1

- lvm2/pkg.yaml
See https://github.com/siderolabs/talos/issues/9365
This allows to break dependency on `/var` availability, and also workaround issue with `/var/run` being persistent on Talos right now (which is going to be fixed as well).
> fix: force LVM to use `/run` as state directory

- systemd-udevd/patches/0001-shared-udev-use-SYSCONF_DIR-instead-of-etc-for-syste.patch
- systemd-udevd/pkg.yaml
This was breaking mdadm system extension. Added a patch to make udev honor the compile-time setting
> fix: systemd-udevd: search for config in /usr/etc

- libselinux/patches/0001-libselinux-exclude-requirement-for-etc-selinux.patch
- libselinux/patches/0001-libselinux-set-free-d-data-to-NULL.patch
- libselinux/pkg.yaml
- libsepol/patches/0001-libsepol-cil-Check-that-sym_index-is-within-bounds.patch
- libsepol/patches/0001-libsepol-sepol_compute_sid-Do-not-destroy-uninitiali.patch
- libsepol/pkg.yaml
We don't use this directory in Talos but load a policy embedded in the init binary.
Also carry upstream fixes for CWEs and a segfault happening in udev without /etc/selinux.
> fix: libselinux: support running without /etc/selinux

- Pkgfile
See https://github.com/opencontainers/runc/releases/tag/v1.2.0
> feat: update runc to 1.2.0

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v2.0.0-rc.6
(cherry picked from commit fc2e8dc07ad096d0394f8deacb20d423ef102c2f)
Backports #1063
> backport: feat: update containerd to v2.0.0-rc.6

- kernel/build/patches/README.md
- kernel/build/patches/netfilter.patch
Thanks to Nico Berlee for pointing this out.
Not going to main, as there likely next release of Linux will already contain it.
> fix: apply netfilter ipv6 fix

- Pkgfile
See https://github.com/opencontainers/runc/releases/tag/v1.2.1
> feat: update runc to v1.2.1

- libselinux/pkg.yaml
- libsepol/patches/dont-build-utils.patch
- libsepol/pkg.yaml
Utilities end up on rootfs increasing size and binary count
Fixes #1067
> fix: do not build unneeded utilities and man for SELinux libraries

- kernel/prepare/pkg.yaml
The tools are now built with non-widecharacter ncurses, so remove the hacks.
Fixes #1084
There's another issue with `BUILDKIT_MULTIPLATFORM`, but that's a separate one.
> chore: fix menuconfig build

- .kres.yaml
- Makefile
- Pkgfile
- e2fsprogs/pkg.yaml
- reproducibility/pkg.yaml
Add e2fsprogs.
Part-of: https://github.com/siderolabs/talos/issues/9746
> feat: add e2fsprogs

- systemd-udevd/pkg.yaml
This allows to see which rules are not present (speficially for 80-net-name-rules, which is not present at all).
> chore: drop the -f flag for rm for udev build

- .kres.yaml
- Makefile
- Pkgfile
- iptables/pkg.yaml
- libmnl/pkg.yaml
- libnftnl/pkg.yaml
Build iptables with nftables support, and force to use nft version.
See https://github.com/siderolabs/talos/issues/9883
> feat: build host iptables with nftables support

- kernel/kernel/pkg.yaml
Drop unused kernel signing public key copy. This was used when the integration tests used a `module-sig-verify`, now we verify certs in extension integration tests by actually loading them.
> chore: drop unused cert copy

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.12.9

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Also update Linux firmware to 20250109
> feat: update Linux to 6.2.10

- cni/pkg.yaml
They are used e.g. by `talosctl` when they run on the host which can be not musl-based.
> fix: build CNI plugins statically linked

- musl/patches/0001-iconv-fix-erroneous-input-validation-in-EUC-KR-decod.patch
- musl/patches/0002-iconv-harden-UTF-8-output-code-path-against-input-de.patch
- musl/pkg.yaml
Ref: https://www.openwall.com/lists/musl/2025/02/13/1
> fix: patch musl to mitigate CVE-2025-26519

- .github/renovate.json
- .kres.yaml
- Makefile
- Pkgfile
- cpio/pkg.yaml
- glib/pkg.yaml
- libburn/pkg.yaml
- libisoburn/pkg.yaml
- libisofs/pkg.yaml
- mtools/pkg.yaml
- pigz/pkg.yaml
- qemu-tools/pkg.yaml
- reproducibility/pkg.yaml
- squashfs-tools/pkg.yaml
- tar/pkg.yaml
- xz/pkg.yaml
- zstd/pkg.yaml
> feat: add tools needed for imager

- kernel/build/patches/README.md
- kernel/build/patches/blackhole.patch
- kernel/build/pkg.yaml
See https://github.com/siderolabs/talos/issues/9837
This causes invalid Ethernet packets to be sent out, which might trigger unrelated issues in some environments.
See:
* git.kernel.org/netdev/net/c/0e4427f8f587
* lore.kernel.org/netdev/20250210084931.23a5c2e4@hermes.local/T
> fix: patch Linux with blackhole patch

- kernel/build/pkg.yaml
This change adds the `-@` flag to the Device Tree Compiler (DTC) flags during the compilation of Device Tree Blobs (DTBs) for the arm64 architecture, enabling proper support for device tree overlays.
**Motivation**
Device tree overlays require the base DTB to include a `/__symbols__` node, which contains the addresses of symbols.  This node is only generated when DTC is invoked with the `-@` flag.  Without this flag, applying overlays results in the following error:
> failed on fdt_overlay_apply(): FDT_ERR_BADMAGIC
> base fdt does not have a /\_\_symbols\_\_ node
> make sure you've compiled with -@
This change is a requirement for enabling device tree overlay support in the [sbc-rockchip](https://github.com/siderolabs/sbc-rockchip), where I am currently integrating this functionality. …
> feat(kernel): add -@ to dtc flags for arm64 to enable overlay support

- containerd/patches/restart.patch
- containerd/pkg.yaml
See https://github.com/containerd/containerd/pull/10853
See https://github.com/containerd/containerd/issues/10848
The observed problem during conformance run:
```
172.20.0.6: {"error":"failed to recover state: failed to get metadata for stored sandbox \"43df4075ab8430af79cc44619b7a0677f581b0c06c1cef63363de25763e5a3a7\": not found","level":"fatal","msg":"Failed to run CRI service","time":"2025-03-13T13:09:27.195325690Z"}
```
> fix: patch containerd with restart fix

- Pkgfile
See:
* https://github.com/containerd/containerd/releases/tag/v2.0.4
* https://github.com/opencontainers/runc/releases/tag/v1.2.6
> feat: update containerd 2.0.4, runc 1.2.6

- containerd/pkg.yaml
This PR enables the Talos containerd package build to provide ctr as part of the Talos releases. ctr is often used for:
- Allows for easy debugging and troubleshooting container issues at the runtime level
- Provides visibility into certain container events as well as container data
Providing ctr as part of the builds in this repo ensures that the ctr version easily lines up with the released containerd version as well as makes it easier for testing, support, and certification with the Talos builds. Alternatively, it might be preferred to have ctr delivered as an extension instead. So, I will open a PR in the extensions repo in case a ctr extension is preferred instead of providing ctr by default as part of the Talos pkg builds.
> feat(containerd): provide ctr as part of the default containerd Talos build

- qemu-tools/pkg.yaml
Now it contains only `qemu-img`.
I believe we don't need any other binary, and the removed binaries are quite big.
```
-rwxr-xr-x 0/0          461536 2019-06-02 01:34 usr/bin/qemu-edid
-rwxr-xr-x 0/0         1518544 2019-06-02 01:34 usr/bin/qemu-io
-rwxr-xr-x 0/0         1635792 2019-06-02 01:34 usr/bin/qemu-nbd
-rwxr-xr-x 0/0          706672 2019-06-02 01:34 usr/bin/qemu-pr-helper
-rwxr-xr-x 0/0         2456944 2019-06-02 01:34 usr/bin/qemu-storage-daemon
-rwxr-xr-x 0/0          694288 2019-06-02 01:34 usr/bin/qemu-vmsr-helper
-rwxr-xr-x 0/0           14440 2019-06-02 01:34 usr/libexec/gio-launch-desktop
-rwxr-xr-x 0/0          461472 2019-06-02 01:34 usr/libexec/qemu-bridge-helper
```
> fix: trim qemu-tools

- .kres.yaml
- Makefile
- Pkgfile
- xdma-driver/pkg.yaml
It's all in the title really, however I've tested this significantly and haven't been able to get the modules to load successfully when upgrading using an installer created with the extension that corresponds to this work. 
```
user: warning: [2025-03-21T17:06:41.370911596Z]: [talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module
\"xdma\": module not found"}
```
Even though the extension installs as expected and the filesystem contains the requisite modules:
```
NODE            NAMESPACE   TYPE              ID   VERSION   NAME          VERSION
<redacted>   runtime     ExtensionStatus   0    1         xdma-driver   aefa9a1
``` 
[Companion pr to …
> feat: Add Xilinx DMA drivers to Talos

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
This can be backported to 1.10.0.
> feat: update Linux 6.12.24, containerd 2.0.5

- Pkgfile
See https://github.com/siderolabs/talos/issues/10855
containerd-2.0 is using 2.5.4: https://github.com/containerd/containerd/blob/release/2.0/script/setup/install-seccomp
main (2.1) is using 2.5.5: https://github.com/containerd/containerd/blob/main/script/setup/install-seccomp
2.6.0 might be too new/unsuported.
> fix: downgrade libseccomp to 2.5.5

- containerd/pkg.yaml
libseccomp is only used for runc build.
> fix: containerd build doesn't need seccomp

- Pkgfile
- containerd/pkg.yaml
Fixes https://github.com/siderolabs/talos/issues/10855
> fix: build containerd with Go 1.23

- containerd/patches/11741-not-set-sandbox-id-when-use-podsandbox-type.patch
- containerd/pkg.yaml
When updating for containerd 2.1, I assumed the patch is no longer needed, as it was included into containerd, but it turns out it got reverted upstream: https://github.com/containerd/containerd/pull/11793
So bring back the patch in updated form, as otherwise `gvisor` leaves running processes behind on container stop.
> fix: bring back updated containerd gvisor patch

- qemu-tools/pkg.yaml
With #1236 qemu-tools doesn't need vmdk support anymore.
> chore: drop qemu-tools vmdk support

- .kres.yaml
- Makefile
- tenstorrent/pkg.yaml
The `-pkg` suffix was missed for tenstorrent pkg.
> fix: tenstorrent pkg name

- Pkgfile
https://redirect.github.com/containerd/containerd/releases/tag/v2.1.1
Fixes https://github.com/advisories/GHSA-cm76-qm8v-3j95
> feat: update containerd to v2.1.1

- iptables/pkg.yaml
- libattr/pkg.yaml
- libcap2/pkg.yaml
- lvm2/pkg.yaml
- openssl/pkg.yaml
- xfsprogs/pkg.yaml
Clean up binaries that either don't work on Talos (as they are shell scripts), or are not needed (e.g. `openssl`, `getcap`, etc.)
Fixes #1226
> fix: clean up some binaries

- iptables/pkg.yaml
This is a fix up for #1242, as otherwise later copy phase in Talos fails on broken `ip6tables-apply` symlink.
> fix: drop broken symlinks

- cni/pkg.yaml
- containerd/pkg.yaml
- flannel-cni/pkg.yaml
- runc/pkg.yaml
Even though these packages are built using Go, they are not used as
Go modules here. Do not confuse vulnerability scanners which reject
findings based on the package type.
> fix: remove erroneous PURLs

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
|---|---|---|
| git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git | minor | `20250708` -> `20250808` |
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.12.40` -> `6.12.41` |
| https://github.com/a13xp0p0v/kernel-hardening-checker.git | digest | `b9a1a2c` -> `aa94036` |
> feat: update backportable dependencies

- kernel/build/patches/0001-CVE-2025-21751-backport-for-Talos-net-mlx5-HWS-chang.patch
- kernel/build/patches/0002-CVE-2025-37860-backport-for-Talos-sfc-fix-NULL-deref.patch
- kernel/build/patches/README.md
CVEs:
* CVE-2025-21751
* CVE-2025-37860
The actual patches are done by @dsseng.
See https://github.com/siderolabs/talos/issues/11416
> fix: backport CVE kernel patches to 6.12

- kernel/build/config-amd64
- kernel/build/config-arm64
Adds support for the IPVS scheduler that uses maglev hashing. Fixes https://github.com/siderolabs/pkgs/issues/1326.
> Enable Kernel config options for IPVS Maglev hashing scheduler support

- nftables/pkg.yaml
Otherwise it links with libgmp, which we don't ship in Talos rootfs.
> fix: build nftables with embedded gmp

- Pkgfile
urcu has the git under AI protection now, so it can'be scraped, switch to GitHub mirror.
> chore: fix renovate config for urcu & hailort
