siderolabs/pkgs

- pkg.yaml
This PR will upgrade to a later stable kernel
> chore: upgrade kernel to 5.2.18

- .drone.yml
- pkg.yaml
> chore: update containerd to 1.3.0

- kmod/pkg.yaml
- util-linux/pkg.yaml
The util-linux and kmod packages should set the --prefix=/.
> fix: set prefix to /

- containerd/pkg.yaml
This version of containerd looks for containerd-shim-runc-v1.
> fix: build containerd-shim-runc-v1

- base/pkg.yaml
- kernel/pkg.yaml
- musl/pkg.yaml
- syslinux/patches/sys-macros.patch
- syslinux/pkg.yaml
> feat: upgrade musl to 1.1.24

- Pkgfile
- base/pkg.yaml
- kernel/pkg.yaml
- musl/pkg.yaml
> chore: use `Pkgfile` vars to expose base image better

- Makefile
- Pkgfile
See talos-systems/toolchain#8, https://github.com/talos-systems/tools/pull/82
> chore: bump tools/toolchain for toolchain refactor

- kernel/config-amd64
- kernel/pkg.yaml
This upgrades Linux to the latest stable version.
> feat: upgrade Linux to 5.3.13

- .drone.yml
- Makefile
This moves to using docker buildx instead of buildctl.
> chore: use docker buildx

- kernel/config-amd64
- kernel/pkg.yaml
Brings in some upstream fixes.
> feat: upgrade Linux to v5.4.8

- kernel/config-amd64
- kernel/pkg.yaml
This brings in the latest stable Linux.
> feat: upgrade Linux to v5.4.10

- kernel/config-amd64
- kernel/pkg.yaml
This brings in the latest stable linux.
> feat: upgrade Linux to v5.4.11

- Makefile
- Pkgfile
Ref: https://github.com/talos-systems/tools/pull/85
Also cleaned up a small nit in Makefile.
> chore: upgrade Go to version 1.13.6

- Pkgfile
See https://github.com/talos-systems/tools/pull/89
> chore: update tools to version with Go 1.14

- Pkgfile
See also talos-systems/tools#90
> feat: upgrade Go to 1.14.1

- Pkgfile
see https://github.com/talos-systems/tools/pull/91
> feat: upgrade Go to 1.14.2

- Makefile
- open-iscsi/patches/libressl-compatibility.patch
- open-iscsi/patches/remove-werror.patch
- open-iscsi/pkg.yaml
- open-isns/pkg.yaml
> feat: add open-iscsi

- Pkgfile
See https://github.com/talos-systems/tools/pull/95.
> feat: update Go to 1.14.5

- kernel/README.md
- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
This updates Linux kernel to the latest available version in 5.7.x
series.
> feat: upgrade Linux kernel to 5.7.14

- Pkgfile
See https://github.com/talos-systems/tools/pull/99
> feat: upgrade Go to 1.14.7

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
This brings in the latest version of Linux 5.7.
> feat: upgrade Linux to v5.7.15

- Pkgfile
- grub/pkg.yaml
This fixes grub-install on EFI machines.
> fix: update GRUB build to build EFI & BIOS platforms

- .drone.yml
- Pkgfile
See https://github.com/talos-systems/tools/pull/102
> feat: upgrade Go to 1.14.8

- Pkgfile
See https://github.com/talos-systems/tools/pull/104
> feat: upgrade Go to 1.15.1

- runc/pkg.yaml
This upgrades runc to the latest stable version.
> feat: upgrade runc v1.0.0-rc92

- .drone.yml
- Makefile
- Pkgfile
> chore: migrate to ghcr.io

- Pkgfile
See https://github.com/talos-systems/tools/pull/110
> feat: bump Go to 1.15.3

- containerd/pkg.yaml
https://github.com/containerd/containerd/releases/tag/v1.4.1
> feat: update containerd to 1.4.1

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
We hope that might fix VMXNET3 issues.
> feat: bump Linux kernel to 5.8.15

- containerd/pkg.yaml
I want variables in `Pkgfile` which are local to the package.
> fix: containerd build 1.4.1

- ca-certificates/pkg.yaml
- cni/pkg.yaml
- cryptsetup/pkg.yaml
- iptables/pkg.yaml
- libressl/pkg.yaml
- libseccomp/pkg.yaml
- linux-firmware/pkg.yaml
- open-iscsi/pkg.yaml
- util-linux/pkg.yaml
- xfsprogs/pkg.yaml
Brings in the latest stable versions.
> feat: bump packages to latest versions

- Pkgfile
See https://github.com/talos-systems/tools/pull/111
> feat: bump Go to 1.15.4

- Pkgfile
> feat: bump Go to 1.15.5

- iptables/pkg.yaml
Address unknown issues with download.
> chore: switch mirror for iptables

- .drone.yml
- Makefile
- Pkgfile
- u-boot/pkg.yaml
> feat: add u-boot

- u-boot/pkg.yaml
This adds support the the Banana Pi M64.
> feat: add support for bpi-m64 in u-boot

- Makefile
- raspberrypi-firmware/pkg.yaml
This adds Raspberry Pi boot firmware.
> feat: add raspberrypi-firmware

- u-boot/pkg.yaml
This builds u-boot for the pine64 rock64.
> feat: build u-boot for rock64

- Pkgfile
See https://github.com/talos-systems/tools/pull/115
> feat: bump Go to 1.15.6

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
> feat: update Linux kernel to 5.9.13

- .conform.yaml
This should enable conformance checks on the PR.
> chore: add conform configuration

- iptables/pkg.yaml
- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
> feat: update Linux to 5.10.14

- Pkgfile
> feat: update Go to 1.15.8

- ca-certificates/pkg.yaml
> feat: update ca-certificates to 2021-01-19

- Pkgfile
- base/pkg.yaml
- u-boot/pkg.yaml
Fix https://github.com/talos-systems/talos/issues/3186
> feat: update u-boot to 2021.01

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
This PR bumps to the latest longterm kernel.
> feat: update kernel to 5.10.19

- Pkgfile
> chore: bump tools to the tag 0.4.0

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.4.4
> feat: update containerd to 1.4.4

- .gitattributes
- u-boot/pkg.yaml
- u-boot/rockpi4/m0/rk3399m0.bin
- u-boot/rockpi4/m0/rk3399m0pmu.bin
- u-boot/rockpi4/patches/platform.mk.patch
This builds u-boot for the Rock Pi 4.
> feat: add u-boot for Rock Pi 4

- Pkgfile
- containerd/pkg.yaml
See https://github.com/talos-systems/tools/pull/131
> feat: bump tools for Go 1.16.1

- Pkgfile
See https://github.com/talos-systems/tools/pull/130
> feat: bump tools for Go 1.15.9

- Pkgfile
See https://github.com/talos-systems/tools/pull/132
> feat: bump tools for Go 1.16.2

- Pkgfile
> feat: build with Go 1.16.3

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
In preparation for Talos 0.10-beta.
> feat: update Linux to 5.10.28

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
Latest release for 5.10.x series.
> feat: update Linux to 5.10.29

- u-boot/pkg.yaml
This add support for the Pine64 and Pine64+ ARM64 SBCs.
> feat: add Pine64 SBC support

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.5.1
> feat: update containerd to 1.5.1

- Pkgfile
See https://github.com/talos-systems/tools/pull/135
> feat: bump tools for Go 1.16.5

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
Lastest release in 5.10 LTS branch.
> feat: update Linux to 5.10.45

- dosfstools/pkg.yaml
https://github.com/dosfstools/dosfstools/releases/tag/v4.2
> chore: update dosfstools to v4.2

- open-iscsi/pkg.yaml
- open-isns/pkg.yaml
* https://github.com/open-iscsi/open-isns/releases/tag/v0.101
* https://github.com/open-iscsi/open-iscsi/releases/tag/2.1.3
* https://github.com/open-iscsi/open-iscsi/releases/tag/2.1.4
> chore: update `open-isns` and `open-iscsi`

- Pkgfile
See https://github.com/talos-systems/tools/pull/140
> feat: update Go to 1.16.6

- Pkgfile
See https://github.com/talos-systems/pkgs/pull/300
> backport: feat: update Go to 1.16.6

- containerd/pkg.yaml
- runc/pkg.yaml
* https://github.com/containerd/containerd/releases/tag/v1.5.3
* https://github.com/opencontainers/runc/releases/tag/v1.0.0
> chore: update runc and containerd

- containerd/pkg.yaml
BUILDTAGS  from https://github.com/containerd/containerd/blob/main/test/build.sh#L32
> feat: disable aufs, devmapper, zfs

- cni/pkg.yaml
- containerd/pkg.yaml
- runc/pkg.yaml
* https://github.com/opencontainers/runc/releases/tag/v1.0.1
* https://github.com/containernetworking/plugins/releases/tag/v0.9.1
> chore: update runc and CNI plugins

- containerd/pkg.yaml
* https://github.com/containerd/containerd/releases/tag/v1.5.4
> chore: update containerd to v1.5.4

- containerd/pkg.yaml
* https://github.com/containerd/containerd/releases/tag/v1.5.5
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> chore: update containerd to v1.5.5

- grub/pkg.yaml
See https://fossies.org/diffs/grub/2.04_vs_2.06/ChangeLog-diff.html
> feat: update GRUB to 2.06

- ca-certificates/pkg.yaml
Bundle was generated at Mon Jul 5 21:35:54 2021 GMT
Signed-off-by: Serge Logvinov <serge.logvinov@sinextra.dev>
> chore: update ca-certificates to 2021-07-05

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
> feat: update Linux to 5.10.58

- eudev/pkg.yaml
See https://github.com/gentoo/eudev/compare/v3.2.9...v3.2.10
> feat: update eudev to 3.2.10

- linux-firmware/pkg.yaml
See https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/
> feat: update linux-firmware to 20210716

- libressl/pkg.yaml
See https://www.libressl.org/releases.html
> feat: update LibreSSL to 3.2.5

- Pkgfile
Update to final release tag, no functional changes.
> chore: update tools to 0.7.0

- Pkgfile
Tools updated to the version which includes new bldr.
> chore: update bldr version, update tools

- fhs/pkg.yaml
See https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf
> /usr/src : Source code (optional)
> feat: add /usr/src to FHS

- containerd/pkg.yaml
- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
- kernel/kernel/scripts/filter-hardened-check.py
> feat: update Linux kernel to 5.10.69

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
> feat: update Linux to 5.10.75

- Pkgfile
To use Go 1.17.3.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
> chore: update tools

- Makefile
> chore: add conformance

- u-boot/pkg.yaml
Updates u-boot to stable release
> feat: update u-boot to 2021.10

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
The latest LTS release in 5.15.x series.
> feat: update Linux to 5.15.4

- kernel/kernel-prepare/pkg.yaml
- kernel/kernel/config-amd64
- kernel/kernel/config-arm64
5.15.3 and 5.15.4 have some issues: https://github.com/talos-systems/talos/issues/4603#issuecomment-980809157
> feat: update Linux to 5.15.5

- Pkgfile
See https://github.com/talos-systems/tools/pull/161
> feat: update Go to 1.17.4

- runc/pkg.yaml
See https://github.com/talos-systems/talos/issues/4648
> feat: update runc to 1.0.3

- Pkgfile
This is the final released version of tools.
> feat: update tools to 0.9.0

- Pkgfile
See https://github.com/talos-systems/tools/pull/164
> feat: update Go to 1.17.5

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
Latest release in the LTS branch.
> feat: update Linux to 5.15.11

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.5.9
> feat: update containerd to 1.5.9

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
See https://www.openwall.com/lists/oss-security/2022/01/18/7
> feat: update Linux to 5.15.16

- Makefile
- libinih/pkg.yaml
- liburcu/pkg.yaml
- xfsprogs/pkg.yaml
This requires libinih, which in turn depends on meson, etc.
> feat: upgrade xfsprogs to the latest version

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.1
> feat: update containerd to 1.6.1

- .conform.yaml
- Makefile
- Pkgfile
- kernel/build/scripts/filter-hardened-check.py
> chore: org update

- u-boot/pkg.yaml
> chore: add rockpi4c

- Makefile
- eudev/pkg.yaml
Bump eudev to 3.2.11
Remove non-relevant default rules
> chore: bump eudev, remove non-relevant default rules

- Pkgfile
See https://github.com/siderolabs/tools/pull/186
> feat: update Go to 1.17.9

- Pkgfile
> chore: bump tools and bldr

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.3
> feat: update containerd to 1.6.3

- Pkgfile
See https://github.com/siderolabs/tools/pull/196
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
> chore: bump Go to 1.17.10

- u-boot/jetson_nano/patches/tegra.patch
- u-boot/pkg.yaml
> chore: bump u-boot v2022.04

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.5
> feat: update containerd to 1.6.5

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.6
> feat: update containerd to 1.6.6

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.50

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.51

- Pkgfile
See https://github.com/siderolabs/tools/pull/211
> feat: update Go to 1.19

- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v1.6.7
> feat: update containerd to 1.6.7

- kernel/build/config-amd64
- kernel/build/config-arm64
- kernel/prepare/pkg.yaml
> chore: bump kernel to 5.15.60

- Pkgfile
This is the version for Talos 1.2.0 release, no changes
to the previous one.
> chore: use final tagged tools image

- containerd/pkg.yaml
Fix version set when building containerd, Ref: #552
> fix: containerd version

- .github/renovate.json
- Pkgfile
- ipxe/pkg.yaml
- socat/pkg.yaml
- Update renovate config to group dependency updates
- Add custom versioning for required packages
> chore: update renovate config

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> chore: bump deps

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Linux 5.15.80
ARM Trusted Firmware 2.8.0
See #574
> chore: update releases

- kernel/build/config-amd64
- kernel/build/config-arm64
* this will help debuging the boot process
> feat: add kernel support for usb serial console

- ipmitool/patches/iana-url.patch
- ipmitool/pkg.yaml
See https://github.com/siderolabs/sidero/issues/1013 
See https://github.com/ipmitool/ipmitool/issues/377
> fix: patch ipmitool IANA URL

- ipmitool/patches/iana-url.patch
- ipmitool/pkg.yaml
See https://github.com/siderolabs/sidero/issues/1013 See https://github.com/ipmitool/ipmitool/issues/377
(cherry picked from commit 165dff6c3cdb2d05f170c8ae0616d9224416455e)
> backport: fix: patch ipmitool IANA URL

- containerd/pkg.yaml
> fix: use proper containerd version tag

- Pkgfile
Release notes https://go.dev/doc/devel/release#go1.19.5
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
> feat: bump Go to 1.19.5

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest LTS update for Talos 1.3.3.
> feat: update Linux to 5.15.89

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Bumping dependencies to prepare Talos 1.3.4 release.
> feat: Linux 5.15.92, containerd 1.6.16

- Pkgfile
> fix: xz url

- drbd/pkg.yaml
- gasket-driver/pkg.yaml
- kernel/kernel/pkg.yaml
- nonfree/kmod-nvidia/pkg.yaml
- nvidia-open-gpu-kernel-modules/pkg.yaml
See https://github.com/siderolabs/talos/issues/6931
> fix: strip kernel modules when installing

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v1.6.20
> feat: update containerd to 1.6.20

- Pkgfile
See https://github.com/siderolabs/tools/pull/286
> chore: update Go to 1.20.3

- Pkgfile
See https://github.com/siderolabs/tools/pull/288
> feat: update Go to 1.20.3

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
See https://github.com/siderolabs/tools/pull/287
> feat: update Go 1.19.8, Linux 5.15.106

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.1.24

- .github/renovate.json
- Makefile
- Pkgfile
- sd-boot/patches/musl.patch
- sd-boot/pkg.yaml
- sd-stub/patches/musl.patch
- sd-stub/pkg.yaml
> feat: add sd-stub and sd-boot

- Pkgfile
Revert to 5.18.0 with an explanation as comment.
> chore: revert xfsprogs

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Enable `ENIC` driver.
Fixes https://github.com/siderolabs/talos/issues/7279
> feat: update Linux to 6.1.30

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Preparing next Talos 1.4 release.
> backport: feat: update Linux to 6.1.30

- Pkgfile
> backport: feat: update Go to 1.20.5

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.1.35

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
- util-linux/pkg.yaml
|---|---|---|
| git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git | minor | `20230515` -> `20230625` | 
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.1.35` -> `6.1.37` | 
| git://git.kernel.org/pub/scm/utils/util-linux/util-linux.git | patch | `2.39` -> `2.39.1` | 
| https://github.com/ipxe/ipxe.git | digest | `2689a6e` -> `e17568a` |
> chore: bump dependencies

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update dependencies

- Makefile
- Pkgfile
- zfs/pkg.yaml
ZFS is a powerful and flexible file system that ensures data integrity and offers features like snapshots and storage pooling.
extension https://github.com/siderolabs/extensions/pull/185
> feat: add 'zfs' package

- .drone.yml
At the moment it is kmod-nvidia.
> chore: enable pushing of non-free packages

- Pkgfile
See https://github.com/opencontainers/runc/releases/tag/v1.1.9
> feat: update runc to 1.1.9

- Makefile
- Pkgfile
Bump `ghcr.io/siderolabs/bldr` and `ghcr.io/siderolabs/tools`.
> feat: update Go to 1.21

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v1.6.23
> feat: update containerd to 1.6.23

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.1.46

- Pkgfile
See https://go.dev/doc/devel/release#go1.21.minor
> feat: update Go to 1.21.1

- Makefile
- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
- openssl/pkg.yaml
|---|---|---|
| [containerd/containerd](https://togithub.com/containerd/containerd) | minor | `v1.6.23` -> `v1.7.6` |
| git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git | minor | `20230804` -> `20230919` |
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.1.54` -> `6.1.55` |
| git://git.openssl.org/openssl.git | patch | `1_1_1v` -> `3.1.3` |
| https://github.com/google/gasket-driver.git | digest | `8aca235` -> `09385d4` |
| https://github.com/ipxe/ipxe.git | digest | `9e99a55` -> `8b14652` |
| [siderolabs/bldr](https://togithub.com/siderolabs/bldr) | patch | `v0.2.1` -> `v0.2.2` |
> feat: update releases

- Pkgfile
See https://github.com/siderolabs/tools/pull/334
> feat: update Go to 1.21.4

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
|---|---|---|
| [containerd/containerd](https://togithub.com/containerd/containerd) | patch | `v1.7.8` -> `v1.7.9` |
| git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git | minor | `20231030` -> `20231111` |
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.1.61` -> `6.1.63` |
| git://repo.or.cz/socat.git | minor | `1.7.4.4` -> `1.8.0.0` |
> feat: bump dependencies

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
> chore: rekres to fix 'failed' build on main

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
> chore: rekres to fix 'failed' build on merge

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v1.7.11
> feat: update containerd to 1.7.11

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.1.69

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.6.14, enable XDP

- Pkgfile
> feat: update Go to 1.20.13

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Pkgfile
> feat: update Go to 1.22

- Pkgfile
See https://github.com/siderolabs/sidero/pull/1316#issuecomment-1953969125
> feat: backport iPXE update from main

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
- kmod/pkg.yaml
|---|---|---|
| [containerd/containerd](https://togithub.com/containerd/containerd) | patch | `v1.7.13` -> `v1.7.14` |
| [containernetworking/plugins](https://togithub.com/containernetworking/plugins) | patch | `v1.4.0` -> `v1.4.1` |
| git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git | minor | `20240220` -> `20240312` |
| git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git | patch | `6.6.20` -> `6.6.21` |
| git://git.kernel.org/pub/scm/utils/cryptsetup/cryptsetup.git | patch | `2.7.0` -> `2.7.1` |
| [siderolabs/bldr](https://togithub.com/siderolabs/bldr) | minor | `v0.2.3` -> `v0.3.0` |
| [tukaani-project/xz](https://togithub.com/tukaani-project/xz) | patch | `v5.6.0` -> `v5.6.1` |
| …
> chore: update dependencies

- .github/renovate.json
- Pkgfile
> chore: remove unused vars

- .kres.yaml
- Makefile
- Pkgfile
See https://github.com/LINBIT/drbd/issues/84#issuecomment-1997793161
> feat: re-enable DRBD

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Preparing for Talos v1.7.0-beta.1.
> feat: update Linux 6.6.26, containerd 1.7.15

- kernel/kernel/pkg.yaml
Fixes the PR https://github.com/siderolabs/pkgs/pull/934
> fix: use proper EFI zBoot image

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Also update linux-firmware to 20240410.
> feat: update Linux to 6.6.28

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Also update linux-firmware to 20240410.
(cherry picked from commit https://github.com/siderolabs/pkgs/commit/dfa7dceb5ae50af454f527ac7c774c93d00054cf)
> backport: feat: update Linux to 6.6.28

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v1.7.16
> feat: update containerd to 1.7.16

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Should fix the `mlx5` issues: https://github.com/siderolabs/talos/issues/8624
> feat: update Linux to 6.6.29

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
PRs backported: 
- #944 
- #947 
- #949
> backports: for v1.7.1

- Pkgfile
> feat: update Linux firmware to 20240513

- Pkgfile
- containerd/pkg.yaml
- libseccomp/pkg.yaml
- runc/pkg.yaml
Update to the latest rc versions, adjust the build to be more aligned with the upstream build process.
> feat: update containerd to 2.0.0-rc.2, runc to 1.2.0-rc.1

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
Version: dc118c53696af6a0b1a8ee78fc9a4d28a217fb21
(cherry picked from commit https://github.com/siderolabs/pkgs/commit/c647a0591741916e4bc28c35dc6a9cc36add65e0)
> backport: feat: update ipxe to the latest

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
> chore: rekres

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
PRs backported:
- #961 
- #966
> backports: for v1.7.3

- Pkgfile
See https://github.com/siderolabs/talos/issues/8910
> feat: update containerd/runc to the next rc versions

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.6.36

- ca-certificates/pkg.yaml
I did an update in tools, but forgot to update pkgs as well.
> fix: update ca-certificates in pkgs

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.6.39

- Pkgfile
- nonfree/kmod-nvidia/lts/pkg.yaml
- nonfree/kmod-nvidia/production/pkg.yaml
- nvidia-open-gpu-kernel-modules/lts/pkg.yaml
- nvidia-open-gpu-kernel-modules/production/pkg.yaml
Bump nvidia drivers and fix renovate detection for nvidia drivers.
> chore: bump nvidia drivers

- ipmitool/patches/iana-url.patch
See https://gitlab.archlinux.org/archlinux/packaging/packages/ipmitool/-/commit/fb71a15a206331bd94f2582e596234214406f861
> fix: reproducible build for ipmitool

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest LTS Linux for Talos 1.8.0-beta.1.
> feat: update Linux to 6.6.51

- Pkgfile
> feat: update Linux firmware to 20240909

- Pkgfile
> feat: update Go to 1.23.2

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v2.0.0-rc.5
> feat: update containerd to v2.0.0-rc.5

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Latest LTS Linux for Talos 1.8.1.
> feat: update Linux to 6.6.54

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.6.58

- Pkgfile
See https://github.com/containerd/containerd/releases/tag/v2.0.0-rc.6
> feat: update containerd to v2.0.0-rc.6

- Pkgfile
- containerd/patches/sandbox-image-pull.patch
- containerd/pkg.yaml
Include the patch https://github.com/containerd/containerd/pull/10917
See https://github.com/siderolabs/talos/issues/9594
> feat: update containerd to v2.0.0

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Also update Linux firmware to 20241110.
> feat: update Linux to 6.6.60

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
See https://github.com/opencontainers/runc/releases/tag/v1.2.2
> feat: update Linux to 6.6.62, runc to 1.2.2

- Pkgfile
Update to final tools 1.9.0.
|---|---|---|
| https://github.com/ipxe/ipxe.git | digest | `8fc11d8` -> `4f7dd7f` |
> feat: bump deps

- Pkgfile
> feat: update Go to 1.23.4

- Pkgfile
See https://github.com/opencontainers/runc/releases/tag/v1.2.3
> feat: update runc to v1.2.3

- Pkgfile
> feat: update Linux firmware to 20241210

- .github/renovate.json
- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
> chore: rekres to bring renovate under kres

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Also update CNI plugins to 1.6.1.
> feat: update Linux to 6.12.6

- containerd/patches/cni-deadlock.patch
- containerd/pkg.yaml
Fixes https://github.com/siderolabs/talos/issues/9984
Patch with https://github.com/containerd/go-cni/pull/126
See also:
* https://github.com/containerd/go-cni/pull/125
* https://github.com/containerd/containerd/issues/11186
* https://github.com/containerd/go-cni/pull/123
> fix: patch containerd with CNI deadlock fix

- Pkgfile
- containerd/patches/cni-deadlock.patch
- containerd/pkg.yaml
- kernel/build/config-amd64
- kernel/build/config-arm64
PRs backported:
- #1121 
- #1127 
- #1128
> backports: for v1.9.1

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Also update runc to 1.2.4:
https://github.com/opencontainers/runc/releases/tag/v1.2.4
> feat: update Linux to 6.12.8

- Pkgfile
- containerd/patches/cni-deadlock.patch
- containerd/pkg.yaml
See https://github.com/containerd/containerd/releases/tag/v2.0.2
> feat: update containerd to v2.0.2

- .github/renovate.json
- Makefile
> chore: rekres to fix reproducibility build

- ca-certificates/pkg.yaml
> fix: certificates CA

- Pkgfile
Via https://github.com/siderolabs/tools/pull/427
> feat: update Go to 1.23.6

- Pkgfile
New patch releases of these dependencies.
Signetd-off-by: Dmitry Sharshakov <dmitry.sharshakov@siderolabs.com>
> chore: systemd 257.3, runc 1.2.5, ipxe

- Pkgfile
- xfsprogs/pkg.yaml
> chore: bump xfsprogs to 6.12.0

- .kres.yaml
- Makefile
- Pkgfile
- glib/pkg.yaml
- zlib/pkg.yaml
Add zlib and export glib deps.
> fix: imager deps

- Pkgfile
Pull in fixed kmod from tools.
> fix: pull in kmod from tools

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Updating backportable dependencies.
> feat: update Linux 6.12.19, Linux firmware 20250311

- .kres.yaml
- Makefile
- Pkgfile
- ena-pkg/pkg.yaml
See https://github.com/siderolabs/talos/issues/10246
> feat: add Amazon ENA Linux driver

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.12.21

- containerd/patches/11741-not-set-sandbox-id-when-use-podsandbox-type.patch
- containerd/pkg.yaml
> fix: backport sandbox fix for Gvisor

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
> feat: update Linux to 6.12.25

- Pkgfile
- containerd/pkg.yaml
PRs backported:
* #1218 
* #1219 
* #1220
> backports: for v1.10.1

- Pkgfile
|---|---|---|
| [openzfs/zfs](https://redirect.github.com/openzfs/zfs) | patch | `2.3.1` -> `2.3.2` |
> feat: update ZFS to 2.3.2

- .github/renovate.json
- .kres.yaml
> fix(renovate): flannel config

- .kres.yaml
- Makefile
- Pkgfile
- tenstorrent/pkg.yaml
Add kernel module for tenstorrent hardware.
I'm a bit stuck on this because the make build isn't working. Still figuring out what I'm missing so feedback welcome.
> feat: add tenstorrent package

- pcre2/pkg.yaml
> fix: drop pcre2 binaries

- Pkgfile
- kernel/build/config-amd64
- kernel/build/config-arm64
Update to the latest LTS version.
> feat: update Linux to 6.12.31

- Pkgfile
There are no new 535.x drivers.
> feat: update NVIDIA drivers to 570.148.08

- grub/pkg.yaml
- mtools/pkg.yaml
See https://www.gnu.org/prep/ftp.html
> chore: use ftpmirror for GNU sources

- .kres.yaml
- Makefile
- Pkgfile
- hailort/pkg.yaml
Add kernel module for hailort Hailo-8L (and others in the family) hardware.
> feat: add hailort package

- iptables/pkg.yaml
> fix: iptables url

- Pkgfile
- cni/pkg.yaml
- containerd/pkg.yaml
- dosfstools/pkg.yaml
- e2fsprogs/pkg.yaml
- flannel-cni/pkg.yaml
- iptables/pkg.yaml
- libaio/pkg.yaml
- libattr/pkg.yaml
- libinih/pkg.yaml
- libjson-c/pkg.yaml
- libmnl/pkg.yaml
- libnftnl/pkg.yaml
- libpopt/pkg.yaml
- liburcu/pkg.yaml
- lvm2/pkg.yaml
- runc/pkg.yaml
- systemd-udevd/pkg.yaml
- xfsprogs/pkg.yaml
> docs: more SBOM metadata to cover whole Talos

- Pkgfile
Fixes SBOM issue in flannel-cni
> fix: bump bldr

- .github/workflows/ci.yaml
- .github/workflows/lock.yml
- .github/workflows/slack-notify.yaml
- .github/workflows/stale.yml
- .github/workflows/weekly.yaml
- Makefile
- Pkgfile
Also use latest bldr and rekres
> feat: bump e2fsprogs, ipxe, kspp, tools

- Pkgfile
The latest 570.x release available right now.
> feat: update NVIDIA production to 570.158.01

- Pkgfile
Updating to tagged releases in preparation for `release-1.11`.
> feat: update tools/toolchain to 1.11.0

- .github/workflows/slack-notify-ci-failure.yaml
- Pkgfile
> feat: update Go to 1.24.6

- .github/workflows/slack-notify-ci-failure.yaml
- Pkgfile
> backport: feat: update Go to 1.24.6

- Pkgfile
Update via tools: https://github.com/siderolabs/tools/pull/472
> feat: update pcre2 to 10.46
